name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
    contents: read
    packages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        logout: false

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/groceries-insomnia:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to Dev
    if: github.ref == 'refs/heads/main'
    env:
      MACHINE: ${{ secrets.REMOTE_HOST }}
    steps:
      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:ci
      - name: Add SSH key
        id: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          MACHINE_IP="$(tailscale ip -6 $MACHINE)"
          ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          sudo apt-get install sshpass

      - name: SSH into Remote Server and Deploy
        run: |
            sshpass -p '${{ secrets.PSWD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} <<'ENDSSH'
            cd ${{ secrets.DEPLOY_PATH }}
            git pull --rebase
            docker compose pull
            docker compose down
            docker compose up -d --force-recreate
            ENDSSH

  test:
    name: Test (using insomnia .yaml export file)
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:ci
      - uses: kong/setup-inso@v1.1.6
        with:
          inso-version: 9.3.4-beta.1
          compression: xz
      - name: (Setup) Add hosts to /etc/hosts
        run: |
          sudo echo "100.126.226.107 dev.groceries.filfreire-t480" | sudo tee -a /etc/hosts

      - run: curl -L dev.groceries.filfreire-t480/health

      - name: Run test suites
        run: inso run test -w insomnia-workspace.yaml "Sanity checks" --env Dev --ci
