name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
    contents: read
    packages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        logout: false

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/groceries-insomnia:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy groceries-app to dev
    if: github.ref == 'refs/heads/main'
    env:
      MACHINE: ${{ secrets.REMOTE_HOST }}
    steps:
      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:ci
      - name: Add SSH key
        id: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          MACHINE_IP="$(tailscale ip -6 $MACHINE)"
          ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keygen -p -f ~/.ssh/key -m PEM

      - name: SSH into Remote Server and Deploy
        run: |
            ssh -i ~/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
            "cd {{ secrets.DEPLOY_PATH }} && docker-compose pull && docker-compose up -d"
